server:
  shutdown: graceful
  port: 8088

spring:
  application:
    name: database-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/database_coursework
    username: mag_db
    password: mag_db
    driver-class-name: org.postgresql.Driver
  secondDatasource:
    url: localhost:27017

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      mode: always