server:
  shutdown: graceful
  port: 8088

spring:
  application:
    name: database-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/database_coursework
    username: mag_db
    password: mag_db
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      host: localhost
      port: 27017
      database: database_coursework

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      mode: always